### ISSUE TITLE
Error: [object Object]

### ISSUE THREAD

**Issue by johnfelipe** [jaimerosales/modelderivative-nodejs-tutorial#2]
i do all this steps:

- I select all API:
![allapi](https://cloud.githubusercontent.com/assets/428820/26538570/44b86932-440d-11e7-9fcc-0378435badfe.png)

- i put all this command in my ubuntu 14:

	git clone https://github.com/jaimerosales/modelderivative-nodejs-tutorial.git
	cd modelderivative-nodejs-tutorial/
	npm install
	cp forge_auth.sh.example forge_auth.sh

- i put this env variables:

	export FORGE_CLIENT_ID='my ID'
	export FORGE_CLIENT_SECRET='My Secret'

	export FORGE_BUCKET_NAME='felipeurregoebimbucket'
	 
	export FORGE_FILE_NAME='20170103CabannaSencilla'
	export FORGE_FILE_PATH='/home/felipe/modelderivative-nodejs-tutorial/20170103CabannaSencilla.rvt'
	export PORT=3020

- This is my revit model: https://drive.google.com/open?id=0B5b2y2kCFpKoNkdFYjhqWE1Ra0E

and this is error show me:

	**** Translating file derivative
	 Error: [object Object]

How can solve this issue?

**Comment by jaimerosales** [comment]
Hi John,

Sorry I was on Vacation last weekend and also at a conference previous to that :).

Your file path will go up from your current location in terminal assuming you are inside of modelderivative-nodejs-tutorial. Meaning it should look like this. 
export FORGE_FILE_PATH='./20170103CabannaSencilla.rvt'
and your file name also needs the extension. 
export FORGE_FILE_NAME='20170103CabannaSencilla.rvt'

This will return you the URN value you need. 

Cheers,

**Comment by johnfelipe** [comment]
is working, this

	**** Getting File Manifest Status
	The status of your file is pending Please wait while we finish Translating your file

is normal?

**Comment by johnfelipe** [comment]
About CallBack URL, this is mine:

CallBack URL
http://200.122.209.134:3020

I think is not OK, right?

**Comment by jaimerosales** [comment]
So this depends, if you are using a 2 legged authentication, you don't need a callback URL, But if you are using a 3 legged one, the callback URL I will suggest to use something else, maybe something like http://myownurl.com/oauth/callback. I will go ahead and marked this as close since your initial question has been answered.
