### ISSUE TITLE
export PORT=?

### ISSUE THREAD

**Issue by johnfelipe** [jaimerosales/modelderivative-nodejs-tutorial#3]
/home/felipe/modelderivative-nodejs-tutorial/forge_auth.sh

##
export PORT=3000
##

That port is something to do with CallBack URL port?
or
That port is something to do with port for viewer?

Im not clear about that
Stay alert

**Comment by jaimerosales** [comment]
So this is probably a mistake on my side, since I'm preparing this tutorial together with the viewer NodeJS one, so I'm setting the PORT for the Viewer load, so this is nothing related to the tutorial on the Model Derivative, I will commented out so it does not confuse others.
